# np.array

In [ ]:
import numpy as np
a = np.array([1,2,3])               #1D
b = np.array([[1,2,3],[3,4,6]])     #2D


## Predefined Functions

In [ ]:
np.zeros((2,3))  #Array of zeros
np.ones((2,3))    #Array of ones
np.full((2,3),7)  #Array of sevens
np.eye(3)        #Identity matrix

## Examples

In [2]:
import numpy as np

def simulate_growth(strains, pH_levels, iron_levels, zinc_levels, temperature):
    # 1. Initialize a 4D array: strain × pH × iron × zinc
    growth_data = np.zeros((len(strains), len(pH_levels), len(iron_levels), len(zinc_levels)))
    
    # 2. Fill array with simulated OD readings (0.5–1.2)
    growth_data = np.random.uniform(0.5, 1.2, growth_data.shape)
    
    # 3. Apply temperature effect (assuming optimal 37°C)
    temp_effect = np.exp(-((temperature - 37)**2) / 50)
    growth_data *= temp_effect
    
    # 4. Normalize OD readings to maximum value
    normalized = growth_data / np.max(growth_data)
    
    # 5. Compute mean growth per strain
    mean_growth = np.mean(normalized, axis=(1,2,3))
    
    # 6. Identify best-performing strain
    best_strain_index = np.argmax(mean_growth)
    best_strain = strains[best_strain_index]
    
    # 7. Compute similarity between strains
    similarity = np.eye(len(strains))
    for i in range(len(strains)):
        for j in range(i+1, len(strains)):
            corr = np.corrcoef(normalized[i].flatten(), normalized[j].flatten())[0,1]
            similarity[i,j] = similarity[j,i] = corr
    
    # 8. Return full results
    return mean_growth, best_strain, similarity


In [3]:
strains = ["Geotrichum candidum", "Lactobacillus plantarum"]
pH_levels = [5.5, 6.0, 6.5]
iron_levels = [1, 2, 3, 4]          # mg/L
zinc_levels = [0.5, 1.0, 1.5, 2.0]  # mg/L
temperature = 37

mean_growth, best_strain, similarity = simulate_growth(strains, pH_levels, iron_levels, zinc_levels, temperature)

print("Average Growth per Strain:", mean_growth)
print("Best Performing Strain:", best_strain)
print("Growth Pattern Similarity Matrix:\n", similarity)


Average Growth per Strain: [0.7583725  0.71287603]
Best Performing Strain: Geotrichum candidum
Growth Pattern Similarity Matrix:
 [[1.         0.05288164]
 [0.05288164 1.        ]]


In [4]:
import numpy as np

# --- Step 1: Define Function (uses conditions, loops, NumPy) ---
def analyze_growth(strains, pH_levels, iron_levels):
    results = {}  # dictionary to store growth results
    
    for strain in strains:  # loop through each strain
        # Step 2: Create base data (using predefined NumPy functions)
        growth = np.zeros((len(pH_levels), len(iron_levels)))  # empty matrix for OD
        
        # Step 3: Simulate OD readings using condition-based logic
        for i, pH in enumerate(pH_levels):
            for j, Fe in enumerate(iron_levels):
                base_growth = np.random.uniform(0.5, 1.2)
                
                # Add logical effects of pH and Fe
                if 5.8 <= pH <= 6.2:
                    base_growth *= 1.1  # near-optimal pH
                if Fe > 3:
                    base_growth *= 0.9  # excess iron slightly toxic
                
                growth[i, j] = round(base_growth, 2)
        
        # Step 4: Normalize growth data
        normalized = growth / np.max(growth)
        
        # Step 5: Store all results
        results[strain] = {
            "raw_data": growth,
            "normalized": normalized,
            "mean_growth": np.mean(normalized)
        }
    
    return results


# --- Step 6: Use function with input data (data types, list comprehension, etc.) ---
strains = ["Geotrichum candidum", "Lactobacillus plantarum"]
pH_levels = [5.5, 6.0, 6.5]
iron_levels = [1, 2, 3, 4]

data = analyze_growth(strains, pH_levels, iron_levels)

# --- Step 7: Find best-performing strain using ternary operator ---
best_strain = max(data, key=lambda s: data[s]["mean_growth"])
summary = f"🥇 Best performing strain: {best_strain}" if data[best_strain]["mean_growth"] > 0.8 else "No strain performed exceptionally."

# --- Step 8: Print all results (using list comprehension for clean format) ---
for s in strains:
    print(f"\n--- {s} ---")
    print("Raw Data:\n", data[s]["raw_data"])
    print("Normalized:\n", data[s]["normalized"])
    print("Mean Growth:", round(data[s]["mean_growth"], 2))

print("\n", summary)



--- Geotrichum candidum ---
Raw Data:
 [[0.76 1.   1.02 0.81]
 [0.89 0.6  1.17 0.92]
 [0.61 0.9  1.15 0.86]]
Normalized:
 [[0.64957265 0.85470085 0.87179487 0.69230769]
 [0.76068376 0.51282051 1.         0.78632479]
 [0.52136752 0.76923077 0.98290598 0.73504274]]
Mean Growth: 0.76

--- Lactobacillus plantarum ---
Raw Data:
 [[0.78 0.85 0.97 0.51]
 [0.87 0.97 0.84 1.06]
 [0.68 1.   1.06 0.82]]
Normalized:
 [[0.73584906 0.80188679 0.91509434 0.48113208]
 [0.82075472 0.91509434 0.79245283 1.        ]
 [0.64150943 0.94339623 1.         0.77358491]]
Mean Growth: 0.82

 🥇 Best performing strain: Lactobacillus plantarum
