## Data_Types_in_Numpy

In [1]:
import numpy as np
## Data_Types_in_Numpy
a = np.array([1, 2, 3])
print(a.dtype)  # Output: int64 (or int32 depending on your system)

int64


In [2]:
a = np.array([1, 2, 3], dtype=np.float32)
print(a.dtype)  # Output: float32

float32


In [3]:
b = a.astype(np.int64)
print(b.dtype)  # Output: int64

int64


## Copy vs View

In [4]:
a = np.array([1,2,3])
v = a.view()
v[0] = 10
print(a)  # Output: [10  2  3]

[10  2  3]


In [5]:
c = a.copy()
c[0] = 20
print(a)  # Output: [10  2  3]
print(c)  # Output: [20  2  3]

[10  2  3]
[20  2  3]


## Broadcasting in NumPy

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = a + b  # Broadcasting happens here 
print(c)  # Output: [[11 22 33] [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = a - b  # Broadcasting happens here 
print(c)  

[[ -9 -18 -27]
 [ -6 -15 -24]]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
c = b - c  # Broadcasting happens here 
print(c)  

[[19 38 57]
 [16 35 54]]


In [7]:
a = np.array([1.0, 2.0, 3.0])
print(a*2)  # Output: [1. 4. 9.]

[2. 4. 6.]


In [13]:
a = np.ones((3,4))
b = np.arange(4)
print((a+b).shape)  

(3, 4)


In [14]:
a = np.ones((5,1,4 ))
b = np.ones((1,3,4))
print((a+b).shape)

(5, 3, 4)


In [15]:
a = np.ones((2,3))
b = np.ones((3,2))
a + b  # This will raise an error due to incompatible shapes

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## Fancy Indexing in NumPy

In [16]:
a = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4] # List of indices to select
print(a[indices])  # Output: [20 40 50]

[20 40 50]


In [22]:
b = np.array([[1, 2], [3, 4], [5, 6]])
rows = [0, 1]
cols = [1, 0]
print(b[rows, cols])  # Output: [2 3]

[2 3]


In [21]:
row = [0,1]
cols = [1,0]
b[row][cols]

array([[1., 1.],
       [1., 1.]])

In [23]:
a = np.array([10, 20, 30, 40, 50])
mask = a > 25
print(a[mask])  # Output: [30 40 50]

[30 40 50]


In [25]:
print(a[(a > 15) & (a < 45)])  # Output: [20 30 40]
print(a[(a > 15) | (a < 45)])  # Output: [10 20 30 40 50]

[20 30 40]
[10 20 30 40 50]


In [26]:
a[a < 30] = 0
print(a)  # Output: [ 0  0 30 40 50]

[ 0  0 30 40 50]


In [31]:
## np.random.rand(d0, d1)
np.random.randn(2,3)  # Standard Normal Distribution


array([[ 0.67175469,  0.34684117,  1.18893622],
       [ 1.32800933, -0.15791724,  0.26548791]])

In [30]:
## np.random.randn(d0,d1)
np.random.randn(3)  # 1D array with 3 elements

array([-0.29537663,  0.37629596, -0.14481443])

In [32]:
## np.random.randint(low, high, size)
np.random.randint(0, 10, 5)  # 1D array with 5 random integers between 0 and 9

array([6, 7, 3, 6, 8], dtype=int32)

In [35]:
## np.random.choice(array, size)
np.random.choice([1,2,3],4)  # Randomly choose 3 elements from the array [1,2,3]

array([3, 1, 1, 2])

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))  # Output: 21
print(np.mean(a))  # Output: 3.5
print(np.std(a))  # Output: Standard deviation of all elements in a
print(np.sum(a, axis=0))  # Output: [5 7 9] (sum of each column)
print(np.sum(a, axis=1))  # Output: [ 6 15] (sum of each row)
print(np.mean(a, axis=0))  # Output: [2.5 3.5 4.5] (mean of each column)
print(np.mean(a, axis=1))  # Output: [2. 5.]
print(np.std(a, axis=0))  # Output: Standard deviation of each column
print(np.std(a, axis=1))  # Output: Standard deviation of each row
print(np.max(a, axis=0))  # Output: [4 5 6] (max of each column)


21
3.5
1.707825127659933
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[2. 5.]
[1.5 1.5 1.5]
[0.81649658 0.81649658]
[4 5 6]


In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.dot(a,b)  # Matrix multiplication
np.matmul(a,b)  # Matrix multiplication
np.transpose(a)  # Transpose of matrix a
np.linalg.inv(a)  # Inverse of matrix a (if a is square and invertible)
np.linalg.det(a)  # Determinant of matrix a (if a is square)
np.linalg.eig(a)  # Eigenvalues and eigenvectors of matrix a (if a is square)
np.linalg.svd(a)  # Singular Value Decomposition of matrix a

LinAlgError: Last 2 dimensions of the array must be square

In [39]:
a = np.arange(20).reshape(4,5)
print(a[1:3,[0,2,4]])  # Select rows 1 to 2 and columns 0, 2, 4

[[ 5  7  9]
 [10 12 14]]
